

[build]
base = "netlify/"
publish = "public/"
command = """\
node_modules/.bin/antora --fetch --generator=@antora/xref-validator ../$STAGE-playbook.yml || true; \
node_modules/.bin/antora --redirect-facility=netlify ../$STAGE-playbook.yml \
"""

[build.environment]
NODE_VERSION = "10"
ANTORA_CACHE_DIR = "node_modules/.cache/antora"
STAGE = "staging"
