site:
  title: OpenZeppelin
  url: https://docs.openzeppelin.com
  start_page: home::index.adoc
content:
  branches: release/*
  sources:
  - url: .
    branches: HEAD
    start_path: home
  - url: git@github.com:okbel/okbel-operator.git
    branches: [master, 1.2.x, 1.1.x, 1.0.x]
    start_path: docs
asciidoc:
  attributes:
    experimental: ''
    idprefix: '@'
    idseparator: '-@'
    tabs: tabs
    toc: ~
    xrefstyle: short
ui:
  bundle:
    url: https://github.com/okbel/oz-docs-ui/build/ui-bundle.zip
  supplemental_files:
  - path: robots.txt
    contents: |
      User-agent: *
      Disallow: /
  - path: ui.yml
    contents: |
      static_files: [robots.txt]
output:
  dir: ./public
